apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: backend-pdb
  namespace: acros-backend
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: acros-backend

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: worker-pdb
  namespace: acros-workers
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: acros-worker
