replicaCount:
  backend: 2
  worker: 1

image:
  backend:
    repository: aegis/backend
    tag: latest
  worker:
    repository: aegis/sandbox-worker
    tag: latest

resources:
  backend:
    requests:
      cpu: "200m"
      memory: "256Mi"
    limits:
      cpu: "1"
      memory: "1Gi"
  worker:
    requests:
      cpu: "250m"
      memory: "512Mi"
    limits:
      cpu: "1"
      memory: "2Gi"

service:
  backend:
    port: 80

minio:
  enabled: true
  bucket: uploads

s3:
  endpoint: http://minio.aegis-storage:9000
  accessKey: minio
  secretKey: minio123
  useSSL: false

redis:
  address: redis.aegis-storage.svc.cluster.local:6379

mongo:
  uri: mongodb://mongo-0.mongo-svc.aegis-storage.svc.cluster.local:27017
