apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: acros-storage-dev
  namespace: argocd
spec:
  project: acros-project
  source:
    repoURL: "REPLACE_WITH_REPO"
    targetRevision: HEAD
    path: deployment/kubernetes/k8s/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: acros-storage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
